version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: lamoda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres -d lamoda" ]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres:
          condition: service_healthy
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:mysecretpassword@postgres:5432/lamoda?sslmode=disable", "up"]

  myapp:
    build:
      context: ../
      dockerfile: ./devops/Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - postgres
      - migrate

volumes:
  postgres_data: